# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'devkit.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(989, 735)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.code = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.code.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(8)
        self.code.setFont(font)
        self.code.setObjectName("code")
        self.horizontalLayout.addWidget(self.code)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.display = QtWidgets.QGraphicsView(self.centralwidget)
        self.display.setObjectName("display")
        self.verticalLayout.addWidget(self.display)
        self.keyboard = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(8)
        self.keyboard.setFont(font)
        self.keyboard.setObjectName("keyboard")
        self.verticalLayout.addWidget(self.keyboard)
        self.keyboard_buffer = QtWidgets.QLabel(self.centralwidget)
        self.keyboard_buffer.setWordWrap(True)
        self.keyboard_buffer.setObjectName("keyboard_buffer")
        self.verticalLayout.addWidget(self.keyboard_buffer)
        self.registers = QtWidgets.QTableWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.registers.setFont(font)
        self.registers.setObjectName("registers")
        self.registers.setColumnCount(1)
        self.registers.setRowCount(12)
        item = QtWidgets.QTableWidgetItem()
        self.registers.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.registers.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.registers.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.registers.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.registers.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.registers.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.registers.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.registers.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.registers.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.registers.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.registers.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.registers.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.registers.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.registers.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.registers.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.registers.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.registers.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.registers.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.registers.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.registers.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.registers.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.registers.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.registers.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.registers.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.registers.setItem(11, 0, item)
        self.registers.horizontalHeader().setDefaultSectionSize(110)
        self.registers.horizontalHeader().setMinimumSectionSize(46)
        self.registers.verticalHeader().setDefaultSectionSize(20)
        self.verticalLayout.addWidget(self.registers)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(300, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.shipIcon = QtWidgets.QPushButton(self.groupBox)
        self.shipIcon.setEnabled(False)
        self.shipIcon.setGeometry(QtCore.QRect(110, 350, 89, 201))
        self.shipIcon.setObjectName("shipIcon")
        self.thruster0 = QtWidgets.QLabel(self.groupBox)
        self.thruster0.setGeometry(QtCore.QRect(110, 560, 67, 17))
        self.thruster0.setObjectName("thruster0")
        self.thruster1 = QtWidgets.QLabel(self.groupBox)
        self.thruster1.setGeometry(QtCore.QRect(180, 560, 67, 17))
        self.thruster1.setObjectName("thruster1")
        self.thruster2 = QtWidgets.QLabel(self.groupBox)
        self.thruster2.setGeometry(QtCore.QRect(110, 320, 67, 17))
        self.thruster2.setObjectName("thruster2")
        self.thruster3 = QtWidgets.QLabel(self.groupBox)
        self.thruster3.setGeometry(QtCore.QRect(190, 320, 67, 17))
        self.thruster3.setObjectName("thruster3")
        self.thruster4 = QtWidgets.QLabel(self.groupBox)
        self.thruster4.setGeometry(QtCore.QRect(80, 360, 67, 17))
        self.thruster4.setObjectName("thruster4")
        self.thruster5 = QtWidgets.QLabel(self.groupBox)
        self.thruster5.setGeometry(QtCore.QRect(80, 520, 67, 17))
        self.thruster5.setObjectName("thruster5")
        self.thruster6 = QtWidgets.QLabel(self.groupBox)
        self.thruster6.setGeometry(QtCore.QRect(220, 360, 67, 17))
        self.thruster6.setObjectName("thruster6")
        self.thruster7 = QtWidgets.QLabel(self.groupBox)
        self.thruster7.setGeometry(QtCore.QRect(220, 520, 67, 17))
        self.thruster7.setObjectName("thruster7")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(130, 360, 67, 17))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.groupBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 989, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpenBinFile = QtWidgets.QAction(MainWindow)
        self.actionOpenBinFile.setObjectName("actionOpenBinFile")
        self.actionRun = QtWidgets.QAction(MainWindow)
        self.actionRun.setObjectName("actionRun")
        self.actionStep = QtWidgets.QAction(MainWindow)
        self.actionStep.setObjectName("actionStep")
        self.actionReset = QtWidgets.QAction(MainWindow)
        self.actionReset.setObjectName("actionReset")
        self.toolBar.addAction(self.actionOpenBinFile)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionRun)
        self.toolBar.addAction(self.actionStep)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionReset)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CodeSpace DevKit 1.0"))
        self.keyboard.setPlaceholderText(_translate("MainWindow", "Keyboard input..."))
        self.keyboard_buffer.setText(_translate("MainWindow", "TextLabel"))
        item = self.registers.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "A"))
        item = self.registers.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "B"))
        item = self.registers.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "C"))
        item = self.registers.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "X"))
        item = self.registers.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Y"))
        item = self.registers.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "Z"))
        item = self.registers.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "I"))
        item = self.registers.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "J"))
        item = self.registers.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "SP"))
        item = self.registers.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "PC"))
        item = self.registers.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "EX"))
        item = self.registers.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "IA"))
        item = self.registers.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Value"))
        __sortingEnabled = self.registers.isSortingEnabled()
        self.registers.setSortingEnabled(False)
        item = self.registers.item(0, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.registers.item(1, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.registers.item(2, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.registers.item(3, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.registers.item(4, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.registers.item(5, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.registers.item(6, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.registers.item(7, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.registers.item(8, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.registers.item(9, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.registers.item(10, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.registers.item(11, 0)
        item.setText(_translate("MainWindow", "0"))
        self.registers.setSortingEnabled(__sortingEnabled)
        self.groupBox.setTitle(_translate("MainWindow", "Ship"))
        self.shipIcon.setText(_translate("MainWindow", "ship"))
        self.thruster0.setText(_translate("MainWindow", "0"))
        self.thruster1.setText(_translate("MainWindow", "0"))
        self.thruster2.setText(_translate("MainWindow", "0"))
        self.thruster3.setText(_translate("MainWindow", "0"))
        self.thruster4.setText(_translate("MainWindow", "0"))
        self.thruster5.setText(_translate("MainWindow", "0"))
        self.thruster6.setText(_translate("MainWindow", "0"))
        self.thruster7.setText(_translate("MainWindow", "0"))
        self.label.setText(_translate("MainWindow", "FRONT"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionOpenBinFile.setText(_translate("MainWindow", "OpenBinFile"))
        self.actionRun.setText(_translate("MainWindow", "Run"))
        self.actionStep.setText(_translate("MainWindow", "Step"))
        self.actionReset.setText(_translate("MainWindow", "Reset"))
